name: action

on:
  push:
    branches: 
      - main
    paths:
      - '*.py'
      - 'templates/**'
      - 'test/**'
      - 'static/**'
      - '.github/workflows/action.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Running tests
        run: |
          pytest

  build-and-push-to-docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
         push: true
         tags: yahyaosama26/passgenerator:latest


